package com.endgamefinance.ui.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.graphics.vector.ImageVector
import com.composables.icons.lucide.*

/** Selectable icon style for category icons (persisted in AppSettings). */
enum class IconStyle(val key: String, val label: String) {
    MATERIAL("material", "Material"),
    LUCIDE("lucide", "Lucide"),
    ;

    companion object {
        fun fromKey(key: String?): IconStyle =
            entries.firstOrNull { it.key == key } ?: MATERIAL
    }
}

/**
 * Large curated subset of the Material (Filled) icon set for categories, with
 * an optional Lucide skin: the same persisted keys resolve to Lucide vectors
 * when [style] is LUCIDE (falling back to Material where Lucide has no
 * equivalent). Keys are stored in categories.icon — NEVER rename or remove an
 * existing key without a migration, or already-assigned category icons will
 * break. New icons may be appended freely.
 */
object IconCatalog {

    /** Active style; snapshot-backed so icon consumers recompose on change. */
    var style by mutableStateOf(IconStyle.MATERIAL)

    private val materialEntries: List<Pair<String, ImageVector>> = listOf(
        // ---- Food & drink ----
        "restaurant" to Icons.Filled.Restaurant,
        "restaurant_menu" to Icons.Filled.RestaurantMenu,
        "fastfood" to Icons.Filled.Fastfood,
        "cafe" to Icons.Filled.LocalCafe,
        "coffee" to Icons.Filled.Coffee,
        "bar" to Icons.Filled.LocalBar,
        "wine" to Icons.Filled.WineBar,
        "liquor" to Icons.Filled.Liquor,
        "sports_bar" to Icons.Filled.SportsBar,
        "nightlife" to Icons.Filled.Nightlife,
        "pizza" to Icons.Filled.LocalPizza,
        "dining" to Icons.Filled.LocalDining,
        "lunch" to Icons.Filled.LunchDining,
        "dinner" to Icons.Filled.DinnerDining,
        "brunch" to Icons.Filled.BrunchDining,
        "ramen" to Icons.Filled.RamenDining,
        "bakery" to Icons.Filled.BakeryDining,
        "icecream" to Icons.Filled.Icecream,
        "cake" to Icons.Filled.Cake,
        "egg" to Icons.Filled.Egg,
        "kitchen" to Icons.Filled.Kitchen,
        "groceries" to Icons.Filled.LocalGroceryStore,
        "basket" to Icons.Filled.ShoppingBasket,
        // ---- Transport ----
        "car" to Icons.Filled.DirectionsCar,
        "car_rental" to Icons.Filled.CarRental,
        "car_repair" to Icons.Filled.CarRepair,
        "electric_car" to Icons.Filled.ElectricCar,
        "ev_station" to Icons.Filled.EvStation,
        "bus" to Icons.Filled.DirectionsBus,
        "subway" to Icons.Filled.DirectionsSubway,
        "transit" to Icons.Filled.DirectionsTransit,
        "railway" to Icons.Filled.DirectionsRailway,
        "train" to Icons.Filled.Train,
        "tram" to Icons.Filled.Tram,
        "boat" to Icons.Filled.DirectionsBoat,
        "sailing" to Icons.Filled.Sailing,
        "bike" to Icons.Filled.DirectionsBike,
        "pedal_bike" to Icons.Filled.PedalBike,
        "moped" to Icons.Filled.Moped,
        "motorcycle" to Icons.Filled.TwoWheeler,
        "walk" to Icons.Filled.DirectionsWalk,
        "taxi" to Icons.Filled.LocalTaxi,
        "shuttle" to Icons.Filled.AirportShuttle,
        "commute" to Icons.Filled.Commute,
        "shipping" to Icons.Filled.LocalShipping,
        "flight" to Icons.Filled.Flight,
        "flight_takeoff" to Icons.Filled.FlightTakeoff,
        "flight_land" to Icons.Filled.FlightLand,
        "airport" to Icons.Filled.LocalAirport,
        "gas" to Icons.Filled.LocalGasStation,
        "parking" to Icons.Filled.LocalParking,
        // ---- Home & utilities ----
        "home" to Icons.Filled.Home,
        "house" to Icons.Filled.House,
        "apartment" to Icons.Filled.Apartment,
        "cottage" to Icons.Filled.Cottage,
        "villa" to Icons.Filled.Villa,
        "cabin" to Icons.Filled.Cabin,
        "furniture" to Icons.Filled.Chair,
        "bed" to Icons.Filled.Bed,
        "weekend" to Icons.Filled.Weekend,
        "bathtub" to Icons.Filled.Bathtub,
        "countertops" to Icons.Filled.Countertops,
        "deck" to Icons.Filled.Deck,
        "yard" to Icons.Filled.Yard,
        "grass" to Icons.Filled.Grass,
        "florist" to Icons.Filled.LocalFlorist,
        "fireplace" to Icons.Filled.Fireplace,
        "roofing" to Icons.Filled.Roofing,
        "foundation" to Icons.Filled.Foundation,
        "plumbing" to Icons.Filled.Plumbing,
        "handyman" to Icons.Filled.Handyman,
        "tools" to Icons.Filled.Build,
        "construction" to Icons.Filled.Construction,
        "electrical" to Icons.Filled.ElectricalServices,
        "electricity" to Icons.Filled.Bolt,
        "power" to Icons.Filled.Power,
        "light" to Icons.Filled.Lightbulb,
        "thermostat" to Icons.Filled.Thermostat,
        "sensors" to Icons.Filled.Sensors,
        "water" to Icons.Filled.WaterDrop,
        "wifi" to Icons.Filled.Wifi,
        "router" to Icons.Filled.Router,
        "laundry" to Icons.Filled.LocalLaundryService,
        "cleaning" to Icons.Filled.CleaningServices,
        "iron" to Icons.Filled.Iron,
        "microwave" to Icons.Filled.Microwave,
        "blender" to Icons.Filled.Blender,
        // ---- Health & fitness ----
        "hospital" to Icons.Filled.LocalHospital,
        "medical" to Icons.Filled.MedicalServices,
        "medication" to Icons.Filled.Medication,
        "healing" to Icons.Filled.Healing,
        "vaccines" to Icons.Filled.Vaccines,
        "heart_monitor" to Icons.Filled.MonitorHeart,
        "bloodtype" to Icons.Filled.Bloodtype,
        "masks" to Icons.Filled.Masks,
        "emergency" to Icons.Filled.Emergency,
        "psychology" to Icons.Filled.Psychology,
        "fitness" to Icons.Filled.FitnessCenter,
        "self_improvement" to Icons.Filled.SelfImprovement,
        "spa" to Icons.Filled.Spa,
        "run" to Icons.Filled.DirectionsRun,
        "hiking" to Icons.Filled.Hiking,
        "pool" to Icons.Filled.Pool,
        "skiing" to Icons.Filled.DownhillSkiing,
        "snowboard" to Icons.Filled.Snowboarding,
        "skateboard" to Icons.Filled.Skateboarding,
        "surfing" to Icons.Filled.Surfing,
        "soccer" to Icons.Filled.SportsSoccer,
        "basketball" to Icons.Filled.SportsBasketball,
        "baseball" to Icons.Filled.SportsBaseball,
        "tennis" to Icons.Filled.SportsTennis,
        "football" to Icons.Filled.SportsFootball,
        "golf" to Icons.Filled.SportsGolf,
        "hockey" to Icons.Filled.SportsHockey,
        "volleyball" to Icons.Filled.SportsVolleyball,
        "cricket" to Icons.Filled.SportsCricket,
        "mma" to Icons.Filled.SportsMma,
        "motorsports" to Icons.Filled.SportsMotorsports,
        "esports" to Icons.Filled.SportsEsports,
        // ---- Shopping & personal ----
        "cart" to Icons.Filled.ShoppingCart,
        "shopping" to Icons.Filled.ShoppingBag,
        "store" to Icons.Filled.Store,
        "storefront" to Icons.Filled.Storefront,
        "mall" to Icons.Filled.LocalMall,
        "offer" to Icons.Filled.LocalOffer,
        "sell" to Icons.Filled.Sell,
        "loyalty" to Icons.Filled.Loyalty,
        "clothes" to Icons.Filled.Checkroom,
        "diamond" to Icons.Filled.Diamond,
        "watch" to Icons.Filled.Watch,
        "haircut" to Icons.Filled.ContentCut,
        "beauty" to Icons.Filled.Brush,
        "face" to Icons.Filled.Face,
        "gift" to Icons.Filled.CardGiftcard,
        "redeem" to Icons.Filled.Redeem,
        // ---- Entertainment & leisure ----
        "movie" to Icons.Filled.Movie,
        "theater" to Icons.Filled.Theaters,
        "comedy" to Icons.Filled.TheaterComedy,
        "tv" to Icons.Filled.Tv,
        "live_tv" to Icons.Filled.LiveTv,
        "music" to Icons.Filled.MusicNote,
        "library_music" to Icons.Filled.LibraryMusic,
        "album" to Icons.Filled.Album,
        "headphones" to Icons.Filled.Headphones,
        "speaker" to Icons.Filled.Speaker,
        "radio" to Icons.Filled.Radio,
        "podcasts" to Icons.Filled.Podcasts,
        "mic" to Icons.Filled.Mic,
        "piano" to Icons.Filled.Piano,
        "games" to Icons.Filled.SportsEsports,
        "videogame" to Icons.Filled.VideogameAsset,
        "toys" to Icons.Filled.Toys,
        "smart_toy" to Icons.Filled.SmartToy,
        "extension" to Icons.Filled.Extension,
        "casino" to Icons.Filled.Casino,
        "celebration" to Icons.Filled.Celebration,
        "festival" to Icons.Filled.Festival,
        "attractions" to Icons.Filled.Attractions,
        "camera" to Icons.Filled.CameraAlt,
        "photo_camera" to Icons.Filled.PhotoCamera,
        "videocam" to Icons.Filled.Videocam,
        "photo" to Icons.Filled.Photo,
        "collections" to Icons.Filled.Collections,
        "palette" to Icons.Filled.Palette,
        "draw" to Icons.Filled.Draw,
        "color_lens" to Icons.Filled.ColorLens,
        "book" to Icons.Filled.MenuBook,
        "auto_stories" to Icons.Filled.AutoStories,
        "library" to Icons.Filled.LocalLibrary,
        // ---- Travel ----
        "luggage" to Icons.Filled.Luggage,
        "backpack" to Icons.Filled.Backpack,
        "hotel" to Icons.Filled.Hotel,
        "map" to Icons.Filled.Map,
        "explore" to Icons.Filled.Explore,
        "travel_explore" to Icons.Filled.TravelExplore,
        "public" to Icons.Filled.Public,
        "terrain" to Icons.Filled.Terrain,
        "landscape" to Icons.Filled.Landscape,
        "beach" to Icons.Filled.BeachAccess,
        "park" to Icons.Filled.Park,
        "forest" to Icons.Filled.Forest,
        "museum" to Icons.Filled.Museum,
        "castle" to Icons.Filled.Castle,
        "city" to Icons.Filled.LocationCity,
        "place" to Icons.Filled.Place,
        "tour" to Icons.Filled.Tour,
        "ticket" to Icons.Filled.ConfirmationNumber,
        // ---- Education & work ----
        "school" to Icons.Filled.School,
        "science" to Icons.Filled.Science,
        "biotech" to Icons.Filled.Biotech,
        "calculate" to Icons.Filled.Calculate,
        "history_edu" to Icons.Filled.HistoryEdu,
        "class" to Icons.Filled.Class,
        "grade" to Icons.Filled.Grade,
        "trophy" to Icons.Filled.EmojiEvents,
        "premium" to Icons.Filled.WorkspacePremium,
        "military_tech" to Icons.Filled.MilitaryTech,
        "work" to Icons.Filled.Work,
        "business" to Icons.Filled.BusinessCenter,
        "company" to Icons.Filled.Business,
        "badge" to Icons.Filled.Badge,
        "engineering" to Icons.Filled.Engineering,
        "architecture" to Icons.Filled.Architecture,
        "design" to Icons.Filled.DesignServices,
        "gavel" to Icons.Filled.Gavel,
        "balance" to Icons.Filled.Balance,
        "policy" to Icons.Filled.Policy,
        "description" to Icons.Filled.Description,
        "article" to Icons.Filled.Article,
        "assignment" to Icons.Filled.Assignment,
        "print" to Icons.Filled.Print,
        "computer" to Icons.Filled.Computer,
        "laptop" to Icons.Filled.Laptop,
        "keyboard" to Icons.Filled.Keyboard,
        "memory" to Icons.Filled.Memory,
        "storage" to Icons.Filled.Storage,
        "cloud" to Icons.Filled.Cloud,
        "code" to Icons.Filled.Code,
        "terminal" to Icons.Filled.Terminal,
        // ---- Money & finance ----
        "money" to Icons.Filled.AttachMoney,
        "monetization" to Icons.Filled.MonetizationOn,
        "money_bag" to Icons.Filled.Money,
        "payments" to Icons.Filled.Payments,
        "paid" to Icons.Filled.Paid,
        "price_check" to Icons.Filled.PriceCheck,
        "request_quote" to Icons.Filled.RequestQuote,
        "receipt" to Icons.Filled.ReceiptLong,
        "receipt_short" to Icons.Filled.Receipt,
        "bank" to Icons.Filled.AccountBalance,
        "wallet" to Icons.Filled.AccountBalanceWallet,
        "savings" to Icons.Filled.Savings,
        "card" to Icons.Filled.CreditCard,
        "credit_score" to Icons.Filled.CreditScore,
        "atm" to Icons.Filled.LocalAtm,
        "pos" to Icons.Filled.PointOfSale,
        "toll" to Icons.Filled.Toll,
        "currency_exchange" to Icons.Filled.CurrencyExchange,
        "bitcoin" to Icons.Filled.CurrencyBitcoin,
        "trending_up" to Icons.Filled.TrendingUp,
        "trending_down" to Icons.Filled.TrendingDown,
        "chart" to Icons.Filled.ShowChart,
        "bar_chart" to Icons.Filled.BarChart,
        "pie_chart" to Icons.Filled.PieChart,
        "analytics" to Icons.Filled.Analytics,
        "insights" to Icons.Filled.Insights,
        "percent" to Icons.Filled.Percent,
        // ---- Family & people ----
        "pets" to Icons.Filled.Pets,
        "cruelty_free" to Icons.Filled.CrueltyFree,
        "child" to Icons.Filled.ChildCare,
        "child_friendly" to Icons.Filled.ChildFriendly,
        "stroller" to Icons.Filled.Stroller,
        "family" to Icons.Filled.FamilyRestroom,
        "woman" to Icons.Filled.Woman,
        "man" to Icons.Filled.Man,
        "boy" to Icons.Filled.Boy,
        "girl" to Icons.Filled.Girl,
        "elderly" to Icons.Filled.Elderly,
        "people" to Icons.Filled.People,
        "group" to Icons.Filled.Groups,
        "diversity" to Icons.Filled.Diversity3,
        // ---- Symbols & misc ----
        "insurance" to Icons.Filled.Security,
        "shield" to Icons.Filled.Shield,
        "verified" to Icons.Filled.VerifiedUser,
        "lock" to Icons.Filled.Lock,
        "umbrella" to Icons.Filled.Umbrella,
        "church" to Icons.Filled.Church,
        "mosque" to Icons.Filled.Mosque,
        "synagogue" to Icons.Filled.Synagogue,
        "temple_buddhist" to Icons.Filled.TempleBuddhist,
        "temple_hindu" to Icons.Filled.TempleHindu,
        "favorite" to Icons.Filled.Favorite,
        "star" to Icons.Filled.Star,
        "bookmark" to Icons.Filled.Bookmark,
        "label" to Icons.Filled.Label,
        "flag" to Icons.Filled.Flag,
        "interests" to Icons.Filled.Interests,
        "recycling" to Icons.Filled.Recycling,
        "eco" to Icons.Filled.Eco,
        "leaf" to Icons.Filled.EnergySavingsLeaf,
        "sunny" to Icons.Filled.WbSunny,
        "ac_unit" to Icons.Filled.AcUnit,
        "fire" to Icons.Filled.LocalFireDepartment,
        "whatshot" to Icons.Filled.Whatshot,
        "anchor" to Icons.Filled.Anchor,
        "rocket" to Icons.Filled.RocketLaunch,
        "phone" to Icons.Filled.Phone,
        "mobile" to Icons.Filled.PhoneAndroid,
        "tablet" to Icons.Filled.Tablet,
        "headset" to Icons.Filled.Headset,
        "sim" to Icons.Filled.SimCard,
        "battery" to Icons.Filled.BatteryFull,
        "settings" to Icons.Filled.Settings,
        "category" to Icons.Filled.Category,
    )

    // Lucide equivalents for the same persisted keys. Keys absent here fall
    // back to their Material vector, so partial coverage is safe.
    private val lucideOverrides: Map<String, ImageVector> = mapOf(
        // Food & drink
        "restaurant" to Lucide.Utensils,
        "restaurant_menu" to Lucide.UtensilsCrossed,
        "fastfood" to Lucide.Sandwich,
        "cafe" to Lucide.Coffee,
        "coffee" to Lucide.Coffee,
        "bar" to Lucide.Martini,
        "wine" to Lucide.Wine,
        "liquor" to Lucide.Beer,
        "sports_bar" to Lucide.Beer,
        "pizza" to Lucide.Pizza,
        "dining" to Lucide.Utensils,
        "lunch" to Lucide.Sandwich,
        "dinner" to Lucide.UtensilsCrossed,
        "brunch" to Lucide.Croissant,
        "ramen" to Lucide.Soup,
        "bakery" to Lucide.Croissant,
        "cake" to Lucide.Cake,
        "egg" to Lucide.Egg,
        "kitchen" to Lucide.CookingPot,
        "groceries" to Lucide.ShoppingCart,
        "basket" to Lucide.ShoppingBasket,
        // Transport
        "car" to Lucide.Car,
        "car_repair" to Lucide.Wrench,
        "ev_station" to Lucide.PlugZap,
        "bus" to Lucide.Bus,
        "subway" to Lucide.TrainFront,
        "transit" to Lucide.TramFront,
        "railway" to Lucide.TrainTrack,
        "train" to Lucide.TrainFront,
        "tram" to Lucide.TramFront,
        "boat" to Lucide.Ship,
        "sailing" to Lucide.Sailboat,
        "bike" to Lucide.Bike,
        "pedal_bike" to Lucide.Bike,
        "walk" to Lucide.Footprints,
        "taxi" to Lucide.CarTaxiFront,
        "shuttle" to Lucide.BusFront,
        "commute" to Lucide.Car,
        "shipping" to Lucide.Truck,
        "flight" to Lucide.Plane,
        "flight_takeoff" to Lucide.PlaneTakeoff,
        "flight_land" to Lucide.PlaneLanding,
        "airport" to Lucide.Plane,
        "gas" to Lucide.Fuel,
        // Home & utilities
        "home" to Lucide.House,
        "house" to Lucide.House,
        "apartment" to Lucide.Building2,
        "cottage" to Lucide.House,
        "villa" to Lucide.House,
        "cabin" to Lucide.House,
        "furniture" to Lucide.Armchair,
        "bed" to Lucide.Bed,
        "weekend" to Lucide.Sofa,
        "bathtub" to Lucide.Bath,
        "yard" to Lucide.Flower2,
        "grass" to Lucide.Sprout,
        "florist" to Lucide.Flower,
        "fireplace" to Lucide.Flame,
        "plumbing" to Lucide.Wrench,
        "handyman" to Lucide.Hammer,
        "tools" to Lucide.Wrench,
        "construction" to Lucide.HardHat,
        "electrical" to Lucide.PlugZap,
        "electricity" to Lucide.Zap,
        "power" to Lucide.Power,
        "light" to Lucide.Lightbulb,
        "thermostat" to Lucide.Thermometer,
        "sensors" to Lucide.Radar,
        "water" to Lucide.Droplet,
        "wifi" to Lucide.Wifi,
        "router" to Lucide.Router,
        "laundry" to Lucide.WashingMachine,
        "cleaning" to Lucide.Brush,
        "microwave" to Lucide.Microwave,
        // Health & fitness
        "hospital" to Lucide.Hospital,
        "medical" to Lucide.Stethoscope,
        "medication" to Lucide.Pill,
        "healing" to Lucide.Bandage,
        "vaccines" to Lucide.Syringe,
        "heart_monitor" to Lucide.HeartPulse,
        "bloodtype" to Lucide.Droplet,
        "emergency" to Lucide.Siren,
        "psychology" to Lucide.Brain,
        "fitness" to Lucide.Dumbbell,
        "hiking" to Lucide.Mountain,
        "pool" to Lucide.Waves,
        "surfing" to Lucide.Waves,
        "esports" to Lucide.Gamepad2,
        // Shopping & personal
        "cart" to Lucide.ShoppingCart,
        "shopping" to Lucide.ShoppingBag,
        "store" to Lucide.Store,
        "storefront" to Lucide.Store,
        "mall" to Lucide.ShoppingBag,
        "offer" to Lucide.Tag,
        "sell" to Lucide.Tags,
        "loyalty" to Lucide.BadgePercent,
        "clothes" to Lucide.Shirt,
        "diamond" to Lucide.Gem,
        "watch" to Lucide.Watch,
        "haircut" to Lucide.Scissors,
        "beauty" to Lucide.Brush,
        "face" to Lucide.Smile,
        "gift" to Lucide.Gift,
        "redeem" to Lucide.Gift,
        // Entertainment & leisure
        "movie" to Lucide.Film,
        "tv" to Lucide.Tv,
        "live_tv" to Lucide.MonitorPlay,
        "music" to Lucide.Music,
        "library_music" to Lucide.Music,
        "album" to Lucide.Disc,
        "headphones" to Lucide.Headphones,
        "speaker" to Lucide.Speaker,
        "radio" to Lucide.Radio,
        "podcasts" to Lucide.Podcast,
        "mic" to Lucide.Mic,
        "piano" to Lucide.Piano,
        "games" to Lucide.Gamepad2,
        "videogame" to Lucide.Gamepad,
        "toys" to Lucide.ToyBrick,
        "smart_toy" to Lucide.Bot,
        "extension" to Lucide.Puzzle,
        "casino" to Lucide.Dice5,
        "celebration" to Lucide.PartyPopper,
        "festival" to Lucide.Tent,
        "attractions" to Lucide.FerrisWheel,
        "camera" to Lucide.Camera,
        "photo_camera" to Lucide.Camera,
        "videocam" to Lucide.Video,
        "photo" to Lucide.Image,
        "collections" to Lucide.Images,
        "palette" to Lucide.Palette,
        "draw" to Lucide.PenTool,
        "color_lens" to Lucide.Palette,
        "book" to Lucide.BookOpen,
        "auto_stories" to Lucide.BookOpen,
        "library" to Lucide.Library,
        // Travel
        "luggage" to Lucide.Luggage,
        "backpack" to Lucide.Backpack,
        "hotel" to Lucide.Hotel,
        "map" to Lucide.Map,
        "explore" to Lucide.Compass,
        "travel_explore" to Lucide.Globe,
        "public" to Lucide.Globe,
        "terrain" to Lucide.Mountain,
        "landscape" to Lucide.Mountain,
        "park" to Lucide.Trees,
        "forest" to Lucide.Trees,
        "museum" to Lucide.Landmark,
        "castle" to Lucide.Castle,
        "city" to Lucide.Building2,
        "place" to Lucide.MapPin,
        "tour" to Lucide.Flag,
        "ticket" to Lucide.Ticket,
        // Education & work
        "school" to Lucide.GraduationCap,
        "science" to Lucide.FlaskConical,
        "biotech" to Lucide.Microscope,
        "calculate" to Lucide.Calculator,
        "history_edu" to Lucide.Feather,
        "class" to Lucide.BookOpen,
        "grade" to Lucide.Star,
        "trophy" to Lucide.Trophy,
        "premium" to Lucide.Medal,
        "military_tech" to Lucide.Medal,
        "work" to Lucide.Briefcase,
        "business" to Lucide.Briefcase,
        "company" to Lucide.Building,
        "badge" to Lucide.BadgeCheck,
        "engineering" to Lucide.HardHat,
        "architecture" to Lucide.DraftingCompass,
        "design" to Lucide.PenTool,
        "gavel" to Lucide.Gavel,
        "balance" to Lucide.Scale,
        "policy" to Lucide.ShieldCheck,
        "description" to Lucide.FileText,
        "article" to Lucide.Newspaper,
        "assignment" to Lucide.ClipboardList,
        "print" to Lucide.Printer,
        "computer" to Lucide.Monitor,
        "laptop" to Lucide.Laptop,
        "keyboard" to Lucide.Keyboard,
        "memory" to Lucide.Cpu,
        "storage" to Lucide.HardDrive,
        "cloud" to Lucide.Cloud,
        "code" to Lucide.Code,
        "terminal" to Lucide.Terminal,
        // Money & finance
        "money" to Lucide.DollarSign,
        "monetization" to Lucide.CircleDollarSign,
        "money_bag" to Lucide.Banknote,
        "payments" to Lucide.Banknote,
        "paid" to Lucide.BadgeDollarSign,
        "request_quote" to Lucide.FileText,
        "receipt" to Lucide.ReceiptText,
        "receipt_short" to Lucide.Receipt,
        "bank" to Lucide.Landmark,
        "wallet" to Lucide.Wallet,
        "savings" to Lucide.PiggyBank,
        "card" to Lucide.CreditCard,
        "credit_score" to Lucide.Gauge,
        "atm" to Lucide.Banknote,
        "pos" to Lucide.CreditCard,
        "toll" to Lucide.Coins,
        "currency_exchange" to Lucide.ArrowLeftRight,
        "bitcoin" to Lucide.Bitcoin,
        "trending_up" to Lucide.TrendingUp,
        "trending_down" to Lucide.TrendingDown,
        "percent" to Lucide.Percent,
        "insights" to Lucide.Sparkles,
        // Family & people
        "pets" to Lucide.PawPrint,
        "cruelty_free" to Lucide.Rabbit,
        "child" to Lucide.Baby,
        "child_friendly" to Lucide.Baby,
        "stroller" to Lucide.Baby,
        "family" to Lucide.Users,
        "woman" to Lucide.User,
        "man" to Lucide.User,
        "boy" to Lucide.User,
        "girl" to Lucide.User,
        "elderly" to Lucide.PersonStanding,
        "people" to Lucide.Users,
        "group" to Lucide.Users,
        "diversity" to Lucide.HeartHandshake,
        // Symbols & misc
        "insurance" to Lucide.ShieldCheck,
        "shield" to Lucide.Shield,
        "verified" to Lucide.BadgeCheck,
        "lock" to Lucide.Lock,
        "umbrella" to Lucide.Umbrella,
        "church" to Lucide.Church,
        "favorite" to Lucide.Heart,
        "star" to Lucide.Star,
        "bookmark" to Lucide.Bookmark,
        "label" to Lucide.Tag,
        "flag" to Lucide.Flag,
        "interests" to Lucide.Shapes,
        "recycling" to Lucide.Recycle,
        "eco" to Lucide.Leaf,
        "leaf" to Lucide.Leaf,
        "sunny" to Lucide.Sun,
        "ac_unit" to Lucide.Snowflake,
        "fire" to Lucide.Flame,
        "anchor" to Lucide.Anchor,
        "rocket" to Lucide.Rocket,
        "phone" to Lucide.Phone,
        "mobile" to Lucide.Smartphone,
        "tablet" to Lucide.Tablet,
        "headset" to Lucide.Headphones,
        "battery" to Lucide.BatteryFull,
        "settings" to Lucide.Settings,
        "category" to Lucide.Shapes,
        // Coverage completers — Lucide lacks direct twins for these, so the
        // nearest-meaning glyph stands in (keeps the whole catalog switchable).
        "nightlife" to Lucide.Martini,
        "icecream" to Lucide.IceCreamCone,
        "car_rental" to Lucide.KeyRound,
        "electric_car" to Lucide.CarFront,
        "moped" to Lucide.Bike,
        "motorcycle" to Lucide.Bike,
        "parking" to Lucide.SquareParking,
        "countertops" to Lucide.PanelTop,
        "deck" to Lucide.Fence,
        "roofing" to Lucide.Construction,
        "foundation" to Lucide.BrickWall,
        "iron" to Lucide.Shirt,
        "blender" to Lucide.GlassWater,
        "masks" to Lucide.Drama,
        "self_improvement" to Lucide.Sparkles,
        "spa" to Lucide.Flower,
        "run" to Lucide.Footprints,
        "skiing" to Lucide.MountainSnow,
        "snowboard" to Lucide.MountainSnow,
        "skateboard" to Lucide.Activity,
        "soccer" to Lucide.Target,
        "basketball" to Lucide.Target,
        "baseball" to Lucide.Target,
        "tennis" to Lucide.Target,
        "football" to Lucide.Target,
        "golf" to Lucide.Flag,
        "hockey" to Lucide.Activity,
        "volleyball" to Lucide.Target,
        "cricket" to Lucide.Target,
        "mma" to Lucide.Dumbbell,
        "motorsports" to Lucide.Gauge,
        "theater" to Lucide.Drama,
        "comedy" to Lucide.Drama,
        "beach" to Lucide.TreePalm,
        "price_check" to Lucide.BadgeDollarSign,
        "chart" to Lucide.ChartLine,
        "bar_chart" to Lucide.ChartColumn,
        "pie_chart" to Lucide.ChartPie,
        "analytics" to Lucide.ChartLine,
        "mosque" to Lucide.Landmark,
        "synagogue" to Lucide.Landmark,
        "temple_buddhist" to Lucide.Landmark,
        "temple_hindu" to Lucide.Landmark,
        "whatshot" to Lucide.Flame,
        "sim" to Lucide.Smartphone,
    )

    private val byKeyMaterial = materialEntries.toMap()

    /** Catalog in the active style (picker grid + search). */
    val entries: List<Pair<String, ImageVector>>
        get() = if (style == IconStyle.LUCIDE) {
            materialEntries.map { (key, vector) -> key to (lucideOverrides[key] ?: vector) }
        } else {
            materialEntries
        }

    fun get(key: String?): ImageVector? = key?.let {
        if (style == IconStyle.LUCIDE) lucideOverrides[it] ?: byKeyMaterial[it]
        else byKeyMaterial[it]
    }

    fun search(query: String): List<Pair<String, ImageVector>> =
        if (query.isBlank()) entries
        else entries.filter { (key, _) -> key.contains(query.trim().lowercase()) }
}
